# rule reference: http://eslint.org/docs/rules
# individual rule reference: http://eslint.org/docs/rules/NAME-OF-RULE
---
  extends: "airbnb-base"
  env:
   es6: true
   node: true
  rules:
   strict:
    -
     0
   "prefer-spread":
    -
     0
   "no-plusplus":
    -
     error
    -
     allowForLoopAfterthoughts: true
   "prefer-arrow-callback":
    -
     error
    -
     allowNamedFunctions: true
   "no-console":
    -
     0
   "global-require":
    -
     0
   "import/no-dynamic-require":
    -
     0
   "comma-dangle":
    -
     error
    -
     arrays: never
     objects: never
     imports: never
     exports: never
     functions: never
   "prefer-destructuring":
    -
     0
