site_name: Gulp Drupal Stack
docs_dir: docs

pages:
  - Home: index.md
  - Usage: usage.md
  - Features:
    - CSS: features/css.md
    - JS: features/js.md
    - Webpack: features/webpack.md
    - Svg: features/svg.md
    - Icons: features/icons.md
    - Sprite: features/sprite.md
    - Drupal-Drush: features/drupal-drush.md
    - Browsersync: features/browser-sync.md
    - Copy: features/copy.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - toc:
      permalink: True
  - admonition:

extra_css:
  - extra.css
